CREATE TABLE IF NOT EXISTS requests (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  track_id VARCHAR(64) NOT NULL,
  track_title VARCHAR(255) NOT NULL,
  track_artist VARCHAR(255) NOT NULL,
  track_album VARCHAR(255) NOT NULL,
  track_cover VARCHAR(512) NOT NULL,
  track_preview VARCHAR(512) NOT NULL,
  track_link VARCHAR(512) NOT NULL,
  nickname VARCHAR(64) DEFAULT '',
  message VARCHAR(255) DEFAULT '',
  status ENUM('new', 'accepted', 'played', 'declined') NOT NULL DEFAULT 'new',
  request_ip VARCHAR(64) DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS settings (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(64) NOT NULL UNIQUE,
  value VARCHAR(255) NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS push_subscriptions (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  request_id INT UNSIGNED NOT NULL,
  endpoint TEXT NOT NULL,
  p256dh VARCHAR(255) NOT NULL,
  auth VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX (request_id),
  CONSTRAINT fk_push_request_id FOREIGN KEY (request_id) REFERENCES requests(id) ON DELETE CASCADE
);
